# Generated by Django 4.2.3 on 2025-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
