# Generated by Django 4.2.3 on 2025-07-30 09:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_animal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
