# Generated by Django 4.2.3 on 2025-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered')], default='CONFIRMED', max_length=20),
        ),
    ]
