# Generated by Django 4.2.3 on 2025-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
